services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - databases
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

networks:
  databases:
    external: true

volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume-db/postgres
      o: bind
